spin:
  title: '&eHavoc PVP'
  items:
    - EMERALD:1
    - GOLD_HELMET:1
    - GOLD_CHESTPLATE:1
    - GOLD_LEGGINGS:1
    - GOLD_BOOTS:1
    - DIAMOND:1
    - DIAMOND_HELMET:1
    - DIAMOND_CHESTPLATE:1
    - DIAMOND_LEGGINGS:1
    - DIAMOND_BOOTS:1